### ISSUE TITLE
Callback pro setItems() v parametru

### ISSUE THREAD

**Issue by kravcik** [modul-is/form#57]
Nefunkční:
```
$form->addWhisperer('xxxx', 'Search', $this->dataCallback(...))
	->setOnSelectCallback(function(string $id): void
	{
		$this->getPresenter()->redirect('this', ['dealerId' => $id]);
	});
```
Funkční:
```
$form->addWhisperer('xxxx', 'Search', [])
	->setOnSelectCallback(function(string $id): void
	{
		$this->getPresenter()->redirect('this', ['dealerId' => $id]);
	})
        ->setOnSearchChangeCallback($this->dataCallback(...));
```

Teoreticky to může být ok, setItems() by asi taky nemělo volat onSearchCallback().

**Comment by vodictomas** [comment]
upravil jsem to na nastavení `setOnSearchChangeCallback`, aby to fungovalo stejně jako předtím

**Comment by vodictomas** [comment]
nebo případně upravit tak, aby parametr `$items` byl pouze `?array` a callback na data se nastavoval implicitně přes `setOnSearchChangeCallback`

**Comment by vodictomas** [comment]
upravil jsem teda `$items` jen na pole, zkoušel jsem možnosti se `->setItems()` a funguje to dobře
